### ISSUE TITLE
NetCDF4 interface compile error

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf4-python#1]
_From [steven.k...@gmail.com](https://code.google.com/u/111107344459373556548/) on February 02, 2008 10:44:30_

What steps will reproduce the problem? 1. Installing netcdf-4.0-2008013102 on 32- and -64-bit Linux platforms with
the recommended gfortran 4.1.2 flags and libraries, e.g. the following HDF
library.

configure --prefix=/opt/gfortran/netcdf-4.0-2008013102 --enable-netcdf-4
--with-hdf5=/opt/gfortran/hdf5-1.8.0-rc2 --with-zlib=/usr
1. Installing hdf5-1.8.0-rc2 on 32- and 64-bit Linux platforms with the
   recommended gfortran 4.1.2 flags.

configure --prefix=/opt/gfortran/hdf5-1.8.0-rc2 --enable-fortran
--enable-cxx --with-zlib=/usr
1. Attempting to build netCDF4-0.7.3.1 What is the expected output? What do you see instead? The error message, consistent across 4 platforms thus far:

compile options: '-I/opt/gfortran/netcdf-4.0-2008013102/include
-I/opt/gfortran/hdf5-1.8.0-rc2/include
-I/usr/lib/python2.5/site-packages/numpy/core/include
-I/usr/include/python2.5 -c'
gcc: netCDF4.c
netCDF4.c: In function ‘**pyx_pf_7netCDF4_8Variable___init**’:
netCDF4.c:7882: error: ‘NC_CHUNK_SUB’ undeclared (first use in this function)
netCDF4.c:7882: error: (Each undeclared identifier is reported only once
netCDF4.c:7882: error: for each function it appears in.)
netCDF4.c:7905: error: ‘NC_CHUNK_SEQ’ undeclared (first use in this function)
netCDF4.c:8088: warning: passing argument 3 of ‘nc_def_var_chunking’ makes
integer from pointer without a cast
netCDF4.c:8088: error: too many arguments to function ‘nc_def_var_chunking’
netCDF4.c: In function ‘**pyx_pf_7netCDF4_8Variable_chunking’:
netCDF4.c:9836: error: too many arguments to function ‘nc_inq_var_chunking’
netCDF4.c:9963: error: ‘NC_CHUNK_SEQ’ undeclared (first use in this function)
netCDF4.c:9986: error: ‘NC_CHUNK_SUB’ undeclared (first use in this function)
netCDF4.c:10009: error: ‘NC_CHUNK_SIZES’ undeclared (first use in this
function)
netCDF4.c: In function ‘__pyx_pf_7netCDF4_getlibversion’:
netCDF4.c:14529: warning: assignment discards qualifiers from pointer
target type
netCDF4.c: In function ‘initnetCDF4’:
netCDF4.c:20679: warning: integer constant is too large for ‘long’ type
netCDF4.c:20690:62: warning: integer constant is so large that it is unsigned
netCDF4.c:20690: warning: this decimal constant is unsigned only in ISO C90
netCDF4.c:20690: warning: integer constant is too large for ‘long’ type
netCDF4.c: In function ‘__pyx_pf_7netCDF4_8Variable___init**’:
netCDF4.c:7882: error: ‘NC_CHUNK_SUB’ undeclared (first use in this function)
netCDF4.c:7882: error: (Each undeclared identifier is reported only once
netCDF4.c:7882: error: for each function it appears in.)
netCDF4.c:7905: error: ‘NC_CHUNK_SEQ’ undeclared (first use in this function)
netCDF4.c:8088: warning: passing argument 3 of ‘nc_def_var_chunking’ makes
integer from pointer without a cast
netCDF4.c:8088: error: too many arguments to function ‘nc_def_var_chunking’
netCDF4.c: In function ‘__pyx_pf_7netCDF4_8Variable_chunking’:
netCDF4.c:9836: error: too many arguments to function ‘nc_inq_var_chunking’
netCDF4.c:9963: error: ‘NC_CHUNK_SEQ’ undeclared (first use in this function)
netCDF4.c:9986: error: ‘NC_CHUNK_SUB’ undeclared (first use in this function)
netCDF4.c:10009: error: ‘NC_CHUNK_SIZES’ undeclared (first use in this
function)
netCDF4.c: In function ‘__pyx_pf_7netCDF4_getlibversion’:
netCDF4.c:14529: warning: assignment discards qualifiers from pointer
target type
netCDF4.c: In function ‘initnetCDF4’:
netCDF4.c:20679: warning: integer constant is too large for ‘long’ type
netCDF4.c:20690:62: warning: integer constant is so large that it is unsigned
netCDF4.c:20690: warning: this decimal constant is unsigned only in ISO C90
netCDF4.c:20690: warning: integer constant is too large for ‘long’ type
error: Command "gcc -pthread -fno-strict-aliasing -DNDEBUG -O2 -g -pipe
-Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector
--param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic
-fasynchronous-unwind-tables -D_GNU_SOURCE -fPIC -fPIC
-I/opt/gfortran/netcdf-4.0-2008013102/include
-I/opt/gfortran/hdf5-1.8.0-rc2/include
-I/usr/lib/python2.5/site-packages/numpy/core/include
-I/usr/include/python2.5 -c netCDF4.c -o
build/temp.linux-i686-2.5/netCDF4.o" failed with exit status 1 What version of the product are you using? On what operating system? Please provide any additional information below. This version of NetCDF4 will not compile successfully with the
--enable-netcdf-4 flag against versions of HDF5 older than this one.  Russ
Rew tells me that's due to the final change in the HDF5 API before the
release of HDF5 1.8.0.

On the other hand, the NetCDF3 version works fine with NetCDF 3.6.2.

_Original issue: http://code.google.com/p/netcdf4-python/issues/detail?id=1_
