### ISSUE TITLE
some tests fail on python 2.6

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf4-python#497]
Two of the tests appear to depend on things added to unittest in python 2.7:

    ERROR: testing netcdftime
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/gpfs/hps/usrx/local/TDS/1002694/netCDF4-1.2.1/test/tst_netcdftime.py", line 254, in runTest
        with self.assertRaises(AttributeError):
    TypeError: failUnlessRaises() takes at least 3 arguments (2 given)
    ERROR: runTest (tst_vlen.TestInvalidDataType)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/gpfs/hps/usrx/local/TDS/1002694/netCDF4-1.2.1/test/tst_vlen.py", line 84, in runTest
        with self.assertRaisesRegexp(ValueError, 'strings are only supported'):
        AttributeError: 'TestInvalidDataType' object has no attribute 'assertRaisesRegexp'

The tests should either be modified to work on python 2.6, or we should make 2.7 an explicit dependency.

**Comment by jswhit** [comment]
Both of these failures appear to be related to the use of ``assertRaises`` and ``assertRaisesRegexp`` as a context manager, which was added in 2.7.
